name: Build Github Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - run: cd ./mysite
      - run: ls

      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email edkingkong@outlook.com
          git config --global user.name YuiHrsw
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/YuiHrsw/yuihrsw.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "auto commit"
          git push origin gh-pages -f